PREFIX ex: <http://example.org#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
     GRAPH <http://example.org/grafoMedidas> {
  		?obs ex:finDeSemana true .
    }
}
WHERE {
     GRAPH <http://example.org/grafoMedidas> {
          ?obs a sosa:Observation ;
               sosa:resultTime ?fechaCompleta .
    }

  BIND(STRBEFORE(STR(?fechaCompleta), "T") AS ?soloFecha)
  BIND(IRI(CONCAT("http://example.org#dia_", REPLACE(?soloFecha, "-", "_"))) AS ?dia)

    GRAPH <http://example.org/grafoDiasSemana> {
        ?dia a wd:Q573 ;
       		wdt:P361 wd:Q211391 .
    }
}
