PREFIX ex:   <http://example.org#>
PREFIX geo:  <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX sf:   <http://www.opengis.net/ont/sf#>

INSERT {
  GRAPH <http://example.org/grafoSensores> {
    ?sensor ex:enZona ?zona .
  }
}
WHERE {
  GRAPH <http://example.org/grafoSensores> {
    ?sensor geo:hasGeometry ?gPt .
    ?gPt    a sf:Point ;
            geo:asWKT ?wPt .
  }
  GRAPH <http://example.org/grafoLuna> {
    ?zona  geo:hasGeometry ?gPoly .
    ?gPoly a sf:Polygon ;
           geo:asWKT ?wPoly .
  }
  FILTER( geof:sfWithin(?wPt, ?wPoly) )
}

