PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX ex: <http://example.org#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?obs ?p ?o .
}
WHERE {
  ?obs a sosa:Observation ;
       sosa:madeBySensor ?sensor ;
       ex:esNocheAstronomica ?noche ;
       ex:hayBrilloLuna ?luna ;
       sosa:resultTime ?t ;
       ?p ?o .

  FILTER (str(?noche) = "true" && str(?luna) = "False" && ?t >= "2023-09-01T00:00:00+00:00"^^xsd:dateTime && ?t <  "2025-01-31T23:59:59+00:00"^^xsd:dateTime)

}
