PREFIX time: <http://www.w3.org/2006/time#>

SELECT ?int ?g
WHERE {
  GRAPH ?g { ?int a time:ProperInterval . }
  OPTIONAL { ?int time:hasBeginning ?b . }
  OPTIONAL { ?int time:hasEnd       ?e . }
  FILTER( !BOUND(?b) || !BOUND(?e) )
}
